<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>


    <xacro:property name="chassis_length" value="0.5"/>
    <xacro:property name="chassis_width" value="0.5"/>
    <xacro:property name="chassis_height" value="0.25"/>
    <xacro:property name="chassis_mass" value="2.0"/>
    <xacro:property name="wheel_radius" value="0.05"/>
    <xacro:property name="wheel_thickness" value="0.025"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="0.25"/>
    <xacro:property name="wheel_offset_y" value="0.155"/>
    <xacro:property name="wheel_offset_z" value="0.055"/>
    <xacro:property name="caster_wheel_radius" value="0.023"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="0.425"/>
    <xacro:property name="caster_wheel_offset_z" value="0"/>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- BASE LINK -->

    <link name="base_link">

    </link>


    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 0"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Red</material>
    </gazebo>

    <!-- LEFT WHEEL LINK -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0.25 ${wheel_offset_y} 0.025" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>




    <!-- RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0.25 ${-wheel_offset_y} 0.025" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>


    <!-- CASTER WHEEL LINK -->

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel"/>
        <origin xyz="${caster_wheel_offset_x} 0 ${caster_wheel_offset_z}"/>
    </joint>


    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>


    <joint name="caster_wheel2_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel2"/>
        <origin xyz="0.075 0 ${caster_wheel_offset_z}"/>
    </joint>


    <link name="caster_wheel2">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>


    <gazebo reference="caster_wheel2">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>


<!-- Pillar4 -->

      <link name="pillar4_link">
        <visual>
              <geometry>
                  <cylinder radius="0.01" length="0.04"/>
              </geometry>
              <material name="black"/>
          </visual>
          <collision>
              <geometry>
                  <cylinder radius="0.01" length="0.04"/>
              </geometry>
          </collision>
        <xacro:inertial_cylinder mass="0.05" length="0.04" radius="0.01">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
      </link>

    <joint name="pillar4_joint" type="fixed">
          <parent link="chassis"/>
          <child link="pillar4_link"/>
          <origin xyz="0.47 -0.22 0.27" rpy="0 0 0"/>
    </joint>



<!-- Pillar3 -->

      <link name="pillar3_link">
        <visual>
              <geometry>
                  <cylinder radius="0.01" length="0.04"/>
              </geometry>
              <material name="black"/>
          </visual>
          <collision>
              <geometry>
                  <cylinder radius="0.01" length="0.04"/>
              </geometry>
          </collision>
        <xacro:inertial_cylinder mass="0.05" length="0.04" radius="0.01">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
      </link>

    <joint name="pillar3_joint" type="fixed">
          <parent link="chassis"/>
          <child link="pillar3_link"/>
          <origin xyz="0.03 0.22 0.27" rpy="0 0 0"/>
    </joint>


<!-- Pillar2 -->

      <link name="pillar2_link">
        <visual>
              <geometry>
                  <cylinder radius="0.01" length="0.04"/>
              </geometry>
              <material name="black"/>
          </visual>
          <collision>
              <geometry>
                  <cylinder radius="0.01" length="0.04"/>
              </geometry>
          </collision>
        <xacro:inertial_cylinder mass="0.05" length="0.04" radius="0.01">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
      </link>

    <joint name="pillar2_joint" type="fixed">
          <parent link="chassis"/>
          <child link="pillar2_link"/>
          <origin xyz="0.03 -0.22 0.27" rpy="0 0 0"/>
    </joint>

<!-- Pillar1 -->

      <link name="pillar1_link">
        <visual>
              <geometry>
                  <cylinder radius="0.01" length="0.04"/>
              </geometry>
              <material name="black"/>
          </visual>
          <collision>
              <geometry>
                  <cylinder radius="0.01" length="0.04"/>
              </geometry>
          </collision>
        <xacro:inertial_cylinder mass="0.05" length="0.04" radius="0.01">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
      </link>

    <joint name="pillar1_joint" type="fixed">
          <parent link="chassis"/>
          <child link="pillar1_link"/>
          <origin xyz="0.47 0.22 0.27" rpy="0 0 0"/>
    </joint>

 <!-- Upper LINK -->

    <joint name="upper_joint" type="fixed">
        <parent link="base_link"/>
        <child link="upper"/>
        <origin xyz="0 0 0"/>
    </joint>

    <link name="upper">
        <visual>
            <origin xyz="${chassis_length/2}  0 0.645"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} 0.71"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 0.645"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} 0.71"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="0.71">
            <origin xyz="${chassis_length/2} 0 0.645" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="upper">
        <material>Gazebo/Orange</material>
    </gazebo>


</robot>